### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by MerlinK75** [PhysiologicAILab/PhysioKit#3]
If there is an issue in the configuration stage, what worked for me is download the zip file and change the path for the configuration to the path of the new zip

**Comment by jnj256** [comment]
Thanks for sharing this Merlin. 

Just to clarify:

This relates to Step-4 (per Read-Me), for which following steps are recommended, when faced with error/ issue related to configuration file:

- Download the repo (if this has not been done), and extract the zip package.
- While launching the interface by running this command:  physiokit --config <path of config file> ; the path of the config file needs to been correctly specified - by locating the specific config file from the extracted zip package of the repo.

If you get an error saying "physiokit" command is unknown, verify if you have activated the correct Python environment (which was used for installing the PhysioKit), and then following command can be used:
python -m PhyioKit2.main --config <path of config file>
